server:
  port: ${ORDER_SERVICE_PORT:8083}

spring:
  datasource:
    url: ${ORDER_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}
