spring:
  datasource:
    url: jdbc:postgresql://${PRODUCT_DB_HOST:localhost}:${PRODUCT_DB_PORT:5432}/${PRODUCT_DB_NAME:product_db}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'


  cloud:
    openfeign:
      client:
        config:
          order-service:
            connect-timeout: 3000
            read-timeout: 5000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2s
      timeout: 2s

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 26MB

aws:
  s3:
    region: ${AWS_REGION:ap-northeast-2}
    bucket: ${AWS_S3_BUCKET}
    public-url: ${AWS_S3_PUBLIC_URL}

embedding:
  client:
    base-url: ${EMBEDDING_SERVICE_URL:http://localhost:8000}

kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost:9092}
  auto-offset-reset: latest
  product-group-id: product-group
  wishlist-group-id: wishlist-group
  category-group-id: category-group
  leaderboard-group-id: leaderboard-group


resilience4j:
  circuitbreaker:
    configs:
      default:
        # 실패율
        failure-rate-threshold: 50 # 실패율 50%
        wait-duration-in-open-state: 10s # Open 유지 시간 10초

        # 느린 호출
        slow-call-duration-threshold: 3s # 3초 이상 걸리는 호출
        slow-call-rate-threshold: 50 # 느린 호출 50% 넘을 시 Open

        # 슬라이딩 윈도우
        sliding-window-type: COUNT_BASED # 횟수로 계산
        sliding-window-size: 20 # 최근 20번의 호출 결과를 기준

        # 상태 전환
        minimum-number-of-calls: 10 # 최소 호출 수 10번 전까진 계산 X
        permitted-number-of-calls-in-half-open-state: 3 # Half Open 호출 수
        automaticTransitionFromOpenToHalfOpenEnabled: true

        # 장애 예외처리
        ignore-exceptions:
          - feign.FeignException$BadRequest

