spring:
  application:
    name: order-service

  config:
    import: ${CONFIG_SERVER_IMPORT:optional:configserver:http://localhost:8888}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        # 실패율
        failure-rate-threshold: 50 # 실패율 50%
        wait-duration-in-open-state: 10s # Open 유지 시간 10초

        # 느린 호출
        slow-call-duration-threshold: 3s # 3초 이상 걸리는 호출
        slow-call-rate-threshold: 50 # 느린 호출 50% 넘을 시 Open

        # 슬라이딩 윈도우
        sliding-window-type: COUNT_BASED # 횟수로 계산
        sliding-window-size: 20 # 최근 20번의 호출 결과를 기준

        # 상태 전환
        minimum-number-of-calls: 10 # 최소 호출 수 10번 전까진 계산 X
        permitted-number-of-calls-in-half-open-state: 3 # Half Open 호출 수
        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      productService:
        base-config: default
        ignore-exceptions:
          - feign.FeignException$BadRequest
          - feign.FeignException$NotFound
          - feign.FeignException$Conflict