plugins {
    id 'org.springframework.boot'
}

description = 'user-service'

dependencies {
    implementation project(':libs:common')

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Redis 湲곕컲 ?몄쬆 ?좏겙 愿由?
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // JWT 諛쒓툒 諛?寃利?
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'io.github.openfeign:feign-micrometer'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'

    // JUnit?먯꽌 Testcontainer???쒖옉怨?醫낅즺 ?섎챸二쇨린瑜?愿由ы븯湲??꾪븳 ?뺤옣 紐⑤뱢
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    // ?ㅼ젣 PostgreSQL?먯꽌 JPA 留ㅽ븨怨?DB ?쒖빟??寃利앺븯湲??꾪븳 ?뚯뒪??而⑦뀒?대꼫
    testImplementation 'org.testcontainers:testcontainers-postgresql'

    compileOnly 'org.projectlombok:lombok'
    // ?ㅼ젙 硫뷀??곗씠???앹꽦
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
