plugins {
    id 'java-library'
}

description = 'common'

repositories {
    mavenCentral()
}

dependencies {
    api 'org.springframework:spring-web'

    // RFC 9562 표준 UUID v7 식별자를 생성하기 위한 라이브러리
    implementation 'com.github.f4b6a3:uuid-creator:6.1.0'
    implementation 'org.springframework.security:spring-security-core'

    implementation 'org.slf4j:slf4j-api'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework:spring-webmvc'
    implementation 'jakarta.validation:jakarta.validation-api'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    compileOnly 'org.projectlombok:lombok'

    annotationProcessor 'org.springframework.boot:spring-boot-autoconfigure-processor'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
