services:
  k6:
    image: grafana/k6:latest
    working_dir: /scripts
    networks:
      - cc-service-apps_default
    environment:
      - TARGET=local
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=avg,min,med,max,p(90),p(95),p(99)
    volumes:
      - .:/scripts

  k6-all:
    image: grafana/k6:latest
    working_dir: /scripts
    networks:
      - cc-service-apps_default
    environment:
      - TARGET=local
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=avg,min,med,max,p(90),p(95),p(99)
    entrypoint: ["sh", "entrypoint.sh"]
    volumes:
      - .:/scripts

networks:
  cc-service-apps_default:
    external: true
